apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bansalaseemgosampledemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bansalaseemgosampledemo 
    spec:
      containers:
        - name: bansalaseemgosampledemo 
          image: abcacr.azurecr.io/bansalaseemgosampledemo 
          ports:
          - containerPort: 80